const scenes=[
{id:'estrategia',number:'01',pack:'START',title:'Estrategia',definition:'Entendemos el negocio antes de construir.',explanation:'Definimos objetivo, oferta, cliente, recorrido y prioridades. El resultado es un mapa claro de qué construir primero y por qué.',price:'Desde $100.000',adds:'Una dirección concreta y un alcance que evita construir de más.',tone:'strategy'},
{id:'identidad',number:'02',pack:'START',title:'Identidad',definition:'Convertimos la marca en una experiencia digital coherente.',explanation:'Dirección visual, jerarquía, UX/UI, componentes, responsive y microinteracciones para que el negocio sea reconocible y usable.',price:'Desde $100.000',adds:'Una apariencia reconocible, usable y consistente en desktop y mobile.',tone:'identity'},
{id:'website',number:'03',pack:'START',title:'Website',definition:'Creamos el espacio digital central del negocio.',explanation:'Arquitectura, secciones, formularios, CTA, responsive, publicación y base técnica preparada para sumar nuevas capacidades.',price:'Desde $150.000',adds:'Una presencia profesional que ya puede captar oportunidades.',tone:'website'},
{id:'catalogo',number:'04',pack:'START',title:'Catálogo',definition:'Ordenamos lo que vendes para que se entienda y se pueda elegir.',explanation:'Categorías, fichas, precios, imágenes, variantes y CTA. Convierte información dispersa en una oferta comercial clara.',price:'Desde $100.000',adds:'Productos y servicios presentados de forma comprensible y accionable.',tone:'catalog'},
{id:'venta-simple',number:'05',pack:'SELL',title:'Venta Simple',definition:'Habilitamos una primera transacción sin montar un e-commerce complejo.',explanation:'Comprar, reservar, cotizar o enviar un pedido mediante un flujo simple, medible y preparado para crecer.',price:'Desde $150.000',adds:'El sitio deja de mostrar solamente: empieza a convertir.',tone:'sale'},
{id:'pagos',number:'06',pack:'SELL',title:'Pagos',definition:'Conectamos el interés del cliente con una forma real de cobrar.',explanation:'Link de pago, transferencia o pasarela según el modelo del negocio, con confirmación y trazabilidad del evento.',price:'$100.000–$150.000',adds:'Una venta puede completarse sin salir del recorrido comercial.',tone:'payments'},
{id:'reservas',number:'07',pack:'SELL',title:'Reservas',definition:'Organizamos disponibilidad, fechas, horas y cupos.',explanation:'Agenda, selección, confirmación, reprogramación y estados básicos para servicios que dependen de disponibilidad.',price:'Desde $150.000',adds:'El cliente puede elegir y confirmar un espacio sin coordinación manual innecesaria.',tone:'booking'},
{id:'gestion',number:'08',pack:'OS',title:'Gestión',definition:'La información que entra se convierte en operación administrable.',explanation:'Pedidos, clientes, productos, reservas, estados, filtros y paneles para trabajar desde un solo lugar.',price:'Desde $200.000',adds:'Control operacional y trazabilidad después de la venta.',tone:'management'},
{id:'notificaciones',number:'09',pack:'SELL',title:'Notificaciones',definition:'El sistema avisa cuando algo necesita atención.',explanation:'Telegram, correo o alertas para pedidos, reservas, pagos y cambios de estado. El negocio no necesita revisar todo manualmente.',price:'$100.000–$150.000',adds:'Respuesta más rápida y menos riesgo de perder una oportunidad.',tone:'notify'},
{id:'automatizacion-ia',number:'10',pack:'OS',title:'Automatización / IA',definition:'Conectamos acciones para reducir trabajo repetitivo y sumar inteligencia.',explanation:'Pedido → aviso → agenda → seguimiento. Después, IA sobre información real del negocio para asistir atención u operación.',price:'Desde $150.000 por flujo',adds:'Procesos coordinados y una base preparada para inteligencia aplicada.',tone:'automation'},
{id:'link-os',number:'11',pack:'OS',title:'LINK OS',definition:'Las piezas dejan de sentirse separadas y funcionan como sistema.',explanation:'Website, venta, clientes, gestión, automatización, datos e IA bajo una arquitectura común que puede seguir evolucionando.',price:'Se construye por módulos',adds:'Un sistema operativo digital adaptado al negocio, no una plataforma genérica.',tone:'os'}
];

const serviceTree={
 start:{title:'LINK START',subtitle:'Tu negocio en línea',products:{
  estrategia:{title:'Estrategia',price:'Desde $100.000',subs:{diagnostico:['Diagnóstico','Entendemos qué vendes, a quién y qué necesita ocurrir para convertir.'],recorrido:['Recorrido del cliente','Ordenamos descubrimiento, decisión, contacto y siguiente acción.'],roadmap:['Roadmap','Definimos qué construir primero, qué puede esperar y cómo evoluciona.']}},
  identidad:{title:'Identidad',price:'Desde $100.000',subs:{direccion:['Dirección visual','Traducimos la marca a un lenguaje digital consistente.'],ux:['UX/UI','Definimos jerarquía, navegación y componentes.'],responsive:['Responsive','La experiencia se adapta a desktop, tablet y mobile.']}},
  website:{title:'Website',price:'Desde $150.000',subs:{arquitectura:['Arquitectura','Organizamos páginas, secciones y recorridos.'],cta:['Conversión / CTA','Cada sección dirige hacia una acción real.'],publicacion:['Publicación','Configuramos y dejamos la plataforma online.']}},
  catalogo:{title:'Catálogo',price:'Desde $100.000',subs:{categorias:['Categorías','Agrupamos la oferta para que sea fácil explorarla.'],fichas:['Fichas','Cada producto o servicio explica qué es, precio y acción.'],contenido:['Contenido comercial','Ordenamos imágenes, textos, precios y variantes.']}}
 }},
 sell:{title:'LINK SELL',subtitle:'Empieza a vender',products:{
  'venta-simple':{title:'Venta Simple',price:'Desde $150.000',subs:{pedido:['Pedido simple','El cliente selecciona y envía una solicitud estructurada.'],reserva:['Reserva rápida','Un CTA puede llevar a fecha, hora o disponibilidad.'],cotizacion:['Cotización','Capturamos información necesaria para preparar una propuesta.']}},
  pagos:{title:'Pagos',price:'$100.000–$150.000',subs:{link:['Link de pago','Conectamos una acción comercial con un cobro simple.'],pasarela:['Pasarela','Integramos un flujo de pago cuando el negocio lo necesita.'],confirmacion:['Confirmación','Registramos el resultado del pago dentro del proceso.']}},
  reservas:{title:'Reservas',price:'Desde $150.000',subs:{calendario:['Calendario','Presentamos fechas y disponibilidad de manera navegable.'],cupos:['Cupos / horarios','Controlamos espacios disponibles.'],estado:['Estado de reserva','Confirmada, pendiente, reprogramada o cancelada.']}},
  notificaciones:{title:'Notificaciones',price:'$100.000–$150.000',subs:{telegram:['Telegram','Un pedido o reserva puede avisar inmediatamente al equipo.'],correo:['Correo','Confirmaciones y avisos automáticos cuando corresponde.'],eventos:['Eventos del sistema','Cada aviso nace de una acción real y queda trazable.']}}
 }},
 os:{title:'LINK OS',subtitle:'Tu negocio como sistema',products:{
  gestion:{title:'Gestión',price:'Desde $200.000',subs:{dashboard:['Dashboard','Vista central de pedidos, clientes, reservas y estados.'],clientes:['Clientes','Ficha e historial comercial en un mismo lugar.'],operacion:['Operación','Estados, filtros y acciones para el trabajo diario.']}},
  'automatizacion-ia':{title:'Automatización / IA',price:'Desde $150.000 / flujo',subs:{flujos:['Automatizaciones','Conectamos eventos para evitar tareas repetitivas.'],ia:['IA aplicada','La inteligencia trabaja sobre información real y controlada del negocio.'],integraciones:['Integraciones','Conectamos servicios externos cuando agregan una capacidad concreta.']}},
  'link-os':{title:'LINK OS',price:'Por módulos',subs:{sistema:['Sistema operativo','Unifica las capacidades construidas alrededor del modelo real del negocio.'],datos:['Datos y memoria','Conserva contexto comercial y operacional.'],evolucion:['Evolución','Se agregan nuevas capacidades sin rehacer la base.']}}
 }}
};

const qs=(s,p=document)=>p.querySelector(s),qsa=(s,p=document)=>[...p.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));

function mountScenes(){const mount=qs('#sceneMount');mount.innerHTML=scenes.map(s=>`<section class="scroll-scene" id="scene-${s.id}" data-scene="${s.id}"><div class="sticky-stage"><div class="scene-placeholder tone-${s.tone}"><div class="scene-art"><span></span><span></span><span></span><i></i></div></div><div class="scene-overlay"></div><div class="scene-copy"><div class="scene-number">${s.number} · ${s.pack}</div><h2 class="scene-title">${s.title}</h2><p class="scene-definition">${s.definition}</p><p class="scene-explanation"><strong>Cómo funciona.</strong> ${s.explanation}</p><div class="scene-price">${s.price}</div></div><div class="scene-adds"><strong>QUÉ AGREGA AL NEGOCIO</strong><span>${s.adds}</span></div><div class="progress-rail"><div class="progress-fill"></div></div></div></section>`).join('')}
mountScenes();

const sceneEls=qsa('.scroll-scene');let ticking=false;
function sceneProgress(el){const r=el.getBoundingClientRect(),travel=Math.max(1,r.height-innerHeight);return clamp(-r.top/travel)}
function animateScene(el,p){const title=qs('.scene-title',el),def=qs('.scene-definition',el),exp=qs('.scene-explanation',el),price=qs('.scene-price',el),adds=qs('.scene-adds',el),art=qs('.scene-art',el),fill=qs('.progress-fill',el);const phase=(a,b)=>clamp((p-a)/(b-a));const set=(node,a,y=18)=>{node.style.opacity=a;node.style.transform=`translate3d(0,${(1-a)*y}px,0)`};set(title,phase(.02,.16),24);set(def,phase(.14,.34),18);set(exp,phase(.32,.58),16);set(price,phase(.58,.78),12);set(adds,phase(.68,.86),12);fill.style.height=`${p*100}%`;art.style.transform=`translate3d(${(p-.5)*30}px,${(p-.5)*-18}px,0) scale(${1+p*.035}) rotate(${(p-.5)*1.8}deg)`}
function renderScroll(){ticking=false;sceneEls.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight)animateScene(el,sceneProgress(el))})}
addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(renderScroll)}},{passive:true});addEventListener('resize',renderScroll,{passive:true});renderScroll();

function renderMap(packKey,productKey=null,subKey=null){const packList=qs('#packList'),productList=qs('#productList'),subList=qs('#subproductList'),detail=qs('#mapDetail');packList.innerHTML='';Object.entries(serviceTree).forEach(([key,p])=>{const b=document.createElement('button');b.textContent=`${p.title} · ${p.subtitle}`;b.className=key===packKey?'active':'';b.onclick=()=>renderMap(key);packList.appendChild(b)});const pack=serviceTree[packKey],firstProduct=productKey&&pack.products[productKey]?productKey:Object.keys(pack.products)[0];productList.innerHTML='';Object.entries(pack.products).forEach(([key,p])=>{const b=document.createElement('button');b.textContent=p.title;b.className=key===firstProduct?'active':'';b.onclick=()=>renderMap(packKey,key);productList.appendChild(b)});const product=pack.products[firstProduct],firstSub=subKey&&product.subs[subKey]?subKey:Object.keys(product.subs)[0];subList.innerHTML='';Object.entries(product.subs).forEach(([key,[name]])=>{const b=document.createElement('button');b.textContent=name;b.className=key===firstSub?'active':'';b.onclick=()=>renderMap(packKey,firstProduct,key);subList.appendChild(b)});const [name,definition]=product.subs[firstSub];detail.innerHTML=`<div class="map-label">04 · DEFINICIÓN</div><h3>${name}</h3><p>${definition}</p><div class="detail-bottom"><p><strong>Producto:</strong> ${product.title}<br><strong>Pack:</strong> ${pack.title}</p><span class="detail-price">${product.price}</span><br><a href="#scene-${firstProduct}" class="button acid" style="margin-top:12px">Ver en la evolución →</a></div>`}
renderMap('start');qsa('[data-pack-jump]').forEach(btn=>btn.addEventListener('click',()=>{renderMap(btn.dataset.packJump);qs('#mapa').scrollIntoView({behavior:'smooth'})}));

const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)document.documentElement.classList.add('reduced-motion');
window.addEventListener('load',()=>{const b=qs('#boot');requestAnimationFrame(()=>{if(b){b.classList.add('hide');setTimeout(()=>b.remove(),520)}})});

const LINK_SALES={url:'https://zgbnjlrxzvzpigmwidsp.supabase.co',key:'sb_publishable_RE_eqhBaLeaUMHuBjLUY2Q_OZNBm9_A',controlId:'00000000-0000-0000-0000-000000000001',clientId:'d6ae48a9-51ae-4919-8972-f29ff2171b72',projectId:'ddfce96d-2e20-4fae-b922-96776adc5975'};const salesSession=sessionStorage.getItem('link_sales_session')||crypto.randomUUID();sessionStorage.setItem('link_sales_session',salesSession);
async function sbInsert(table,payload){const r=await fetch(`${LINK_SALES.url}/rest/v1/${table}`,{method:'POST',headers:{apikey:LINK_SALES.key,Authorization:`Bearer ${LINK_SALES.key}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok)throw new Error(await r.text());const d=await r.json();return Array.isArray(d)?d[0]:d}
async function trackSalesEvent(eventName,el,payload={}){const scene=el?.closest?.('.scroll-scene');try{await sbInsert('sales_events',{control_id:LINK_SALES.controlId,client_id:LINK_SALES.clientId,project_id:LINK_SALES.projectId,session_id:salesSession,event_type:'interaction',event_name:eventName,cta_id:el?.dataset?.salesCta||el?.id||null,product_key:scene?.dataset?.scene||null,page_path:location.pathname,payload})}catch(e){console.warn('sales event',e)}}
document.addEventListener('click',e=>{const el=e.target.closest('.button,[data-pack-jump],[data-sales-cta]');if(el)trackSalesEvent('cta_click',el,{text:(el.textContent||'').trim().slice(0,120)})});
const salesForm=qs('#sales-form');if(salesForm)salesForm.addEventListener('submit',async e=>{e.preventDefault();const status=qs('#form-status'),fd=new FormData(salesForm);status.className='form-status';status.textContent='Enviando…';try{const lead=await sbInsert('sales_leads',{control_id:LINK_SALES.controlId,client_id:LINK_SALES.clientId,project_id:LINK_SALES.projectId,source:'link-digital-web',source_page:location.pathname,source_cta:'sales-form',full_name:fd.get('full_name'),email:fd.get('email'),phone:fd.get('phone'),company:fd.get('company'),interested_pack:fd.get('interested_pack'),message:fd.get('message'),metadata:{session_id:salesSession,referrer:document.referrer}});await sbInsert('sales_events',{control_id:LINK_SALES.controlId,client_id:LINK_SALES.clientId,project_id:LINK_SALES.projectId,lead_id:lead.id,session_id:salesSession,event_type:'conversion',event_name:'lead_created',cta_id:'sales-form',pack_key:fd.get('interested_pack')||null,page_path:location.pathname,payload:{company:fd.get('company')||null}});status.classList.add('ok');status.textContent='Recibido. Tu solicitud quedó registrada en LINK Digital.';salesForm.reset()}catch(err){console.error(err);status.classList.add('err');status.textContent='No pudimos enviar la solicitud. Intenta nuevamente.'}});